### ISSUE TITLE
Documentation website is down

### ISSUE THREAD

**Issue by shumphrey** [l2beat/earl#286]
https://earljs.dev/api/api-reference.html is currently down

**Comment by krzkaczor** [comment]
Thanks! New URL is: https://earl.fun/

**Comment by shumphrey** [comment]
The README currently refers to the old URLs

**Comment by krzkaczor** [comment]
Yes, thanks! I just fixed it everywhere (i think...).

**Comment by shumphrey** [comment]
Could this be published to npm?
The doc links is still broken on https://www.npmjs.com/package/earljs
